name: Run QA Checks on Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install python
      run:  uv python install 3.13

    - name: Check Quality
      run: make qa
